# Generated by Django 6.0.2 on 2026-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="sociallink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=25)),
                ("link", models.URLField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
    ]
